import { createContext, useState } from 'react';

export const GeneratedTemplatesContext = createContext();

export function GeneratedTemplatesProvider({ children }) {
  const [generatedTemplates, setGeneratedTemplates] = useState(() => {
    const saved = localStorage.getItem('generatedTemplates');
    return saved ? JSON.parse(saved) : [];
  });
  
  const [userPlan, setUserPlan] = useState(() => {
    const savedPlan = localStorage.getItem('userPlan');
    return savedPlan || 'FREE';
  });

  // Check template generation limits based on actual pricing
  const canGenerateMore = () => {
    if (userPlan === 'LIFETIME' || userPlan === 'PRO') {
      return true; // Unlimited generations
    }
    return generatedTemplates.length < 2; // Free users get 2 templates
  };

  const addGeneratedTemplate = (template) => {
    if (!canGenerateMore()) {
      throw new Error('Template limit reached. Purchase lifetime access for unlimited generations!');
    }

    const filteredTemplates = generatedTemplates.filter(
      t => t.templateName !== template.templateName
    );
    
    // Add branding and plan info to template
    const templateWithMeta = {
      ...template,
      generatedAt: new Date().toISOString(),
      planType: userPlan,
      branding: userPlan === 'FREE' ? 'Generated by TC Generator' : ''
    };

    const updatedTemplates = [...filteredTemplates, templateWithMeta];
    setGeneratedTemplates(updatedTemplates);
    localStorage.setItem('generatedTemplates', JSON.stringify(updatedTemplates));
  };

  const clearGeneratedTemplates = () => {
    setGeneratedTemplates([]);
    localStorage.removeItem('generatedTemplates'); // Don't clear plan data
  };

  const setUserPlanAfterPurchase = (planType) => {
    setUserPlan(planType);
    localStorage.setItem('userPlan', planType);
  };

  return (
    <GeneratedTemplatesContext.Provider value={{ 
      generatedTemplates, 
      addGeneratedTemplate,
      clearGeneratedTemplates,
      userPlan,
      setUserPlanAfterPurchase,
      canGenerateMore,
      isLifetimeMember: userPlan === 'LIFETIME',
      isProMember: userPlan === 'PRO'
    }}>
      {children}
    </GeneratedTemplatesContext.Provider>
  );
}