export const SUBSCRIPTION_PLANS = {
  FREE: {
    name: "Free",
    maxTemplates: 2,
    features: ["Basic PDF export", "Standard templates", "Email support"],
    price: 0,
  },
  PRO: {
    name: "Pro",
    maxTemplates: 10,
    features: [
      "PDF & Word export",
      "Custom branding",
      "Priority support",
      "10 templates per month",
      'Remove "Generated by" text',
    ],
    price: 29,
  },
};
